apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ingress-nginx-event-writer
  namespace: default # Important! This is the namespace where your Ingress resources are
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"] # added verbs