apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-node-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: ingress-nginx-node-reader
  apiGroup: rbac.authorization.k8s.io