apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
data:
  proxy-connect-timeout: "600"
  proxy-read-timeout: "600"
  http-port: "80"
  https-port: "443"
