apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-default-backend
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ingress-nginx
