apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080  # Exposed port on the service
      targetPort: 8080  # Internal Keycloak port
      nodePort: 30000  # Expose the service on port 30000 (can be any port between 30000-32767)
  type: NodePort  # Exposes the service externally via a NodePort
